name: ethereum_util
description: a collection of utility functions for Ethereum
version: 1.3.0
author: Peter Chung <touhonoob@gmail.com>
homepage: https://github.com/ethereumdart/ethereum_util

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  meta: ^1.1.6
  convert: ^2.1.1
  quiver: '>=2.0.0 <3.0.0'
  pointycastle: ^1.0.1
  buffer: ^1.0.6
  equatable: ^0.2.3
  collection: ^1.14.11
  json_schema: ^2.2.0
  json_annotation: ^3.0.0

dev_dependencies:
  build_runner: ^1.3.0
  json_serializable: ^3.0.0
  path: ^1.6.2
  test: ^1.6.2
